# Generated by Django 4.1.3 on 2022-12-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expireslink',
            name='link',
            field=models.CharField(default='link', max_length=20),
        ),
    ]
