# Generated by Django 4.1.3 on 2022-12-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(editable=False, upload_to='uploads/thumbs/'),
        ),
    ]
