# Generated by Django 4.1.3 on 2022-12-31 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_image_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='thumbnail',
            new_name='thumbnailimg',
        ),
    ]
