# Generated by Django 4.1.3 on 2022-12-31 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_thumbnail_image_thumbnailimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='thumbnailimg',
            new_name='thumbnail',
        ),
    ]
