# Generated by Django 4.1.3 on 2022-12-17 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
