# Generated by Django 4.1.3 on 2022-12-31 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_image_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='upload',
            new_name='original',
        ),
    ]
