# Generated by Django 4.1.3 on 2023-01-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_image_original_alter_image_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='thumbnails',
            field=models.JSONField(default={}),
        ),
    ]
