# Generated by Django 4.1.3 on 2023-01-02 16:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnailimage',
            name='thumbnail',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
    ]
