# Generated by Django 4.1.3 on 2023-01-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_thumbnailimage_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='thumbnails',
            field=models.JSONField(default=dict),
        ),
    ]
